spring.application.name=GATEWAY-Service
server.port = 8082

eureka.client.service-url.defaultzone = http://localhost:8761/eureka/

# Route 1: servicio1
spring.cloud.gateway.routes[0].id=servicio1
spring.cloud.gateway.routes[0].uri=lb://Saludo-Service
spring.cloud.gateway.routes[0].predicates[0]=Path=/saludo/say/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter